### ISSUE TITLE
Delay ms option for write_read

### ISSUE THREAD

**Issue by mnishiguchi** [elixir-circuits/circuits_i2c#78]
Some devices require certain delay between write and read operations. I just thought it would be nice if `write_read` has a `delay_ms` option so that we can continue to use the function in such a case.

```elixir
# Proposed API
Circuits.I2C.write_read(ref, 0x20, <<0>>, 11, delay: 250)
```

There might be a few approaches:
- Elixir level (we could just combine `write`, `Process.sleep` and `read` sequentially)
- C level (I am not so familiar)

### Notes

- I came up with this idea when I saw this in Adafruit's Python code: https://github.com/adafruit/Adafruit_CircuitPython_SGP40/blob/c627e608325987fc31264da4b5b3cf8afcdaf3e7/adafruit_sgp40.py#L148

**Comment by fhunleth** [comment]
`Circuits.I2C.write_read` isn't a convenience function to save you from calling `Circuits.I2C.write` and then `Circuits.I2C.read`. On every device except for the Raspberry Pi (due to a hardware bug), it creates a single transaction with the I2C device that does both the write and the read. There's no way at a low level to add a delay that I know of, but you wouldn't want to do that since it would tie up the I2C bus and prevent transactions to other I2C devices.

It could be that we could add a delay option and decide at runtime whether or not to split the transaction, but that's seems more confusing than just always trying to make it one transaction. And then if you want two I2C transactions with a delay that you write `I2C.write`, `Process.sleep`, and then `I2C.read` in your code.

**Comment by mnishiguchi** [comment]
Makes sense. Seems like it would be best to leave it to the lib users for simplicity.

Maybe we could add pro tips about it in README so that future user possibly save time for timing issues.
